### ISSUE TITLE
`Frost Nova` weapon special is bugged. 

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#10]
When it is applied it deals the damage three times instead of just once every hit.
Observed by Konrad2

**Comment by knyghtmare** [comment]
Upon further inspection, I have reason to believe that this is caused by how the events have been implemented. In WoL, I just add into the unit files and for the source (DiD), the event has been added via:
`
[+campaign]
    {FROST_NOVA_EVENT}
[/campaign]
`

**Comment by knyghtmare** [comment]
Funny, it just disappeared...Must be the new Wesnoth update?

**Comment by sevu** [comment]
Sounds like the macros were included three times. Maybe each unit type from a line added them once and you don't find it by testing, as it will only show up when a unit advanced.

Giving the events and id is what I did in such cases. But there's also the new [load_resource].
