### ISSUE TITLE
BUG: ability lithic idol is buggy

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#163]
- Does not seem to work during morning time
- The healing effect seems to not work either

**Comment by babaissarkar** [comment]
More details?
I put a Forgotton Minotaur in a scenario start (time: morning 1/6). What I noticed that the ability kicked in at the next turn, and in the initial turn I could move the unit or attack with it. Is this the bug?

**Comment by knyghtmare** [comment]
> More details? I put a Forgotton Minotaur in a scenario start (time: morning 1/6). What I noticed that the ability kicked in at the next turn, and in the initial turn I could move the unit or attack with it. Is this the bug?

Yeah, the bug is that the special does not trigger for morning time, or any time of the day if it's not side 1. It's weird.

**Comment by Refumee** [comment]
For me it is working as intented. They turn to stone and heal 10 hitpoints.
There is no healing animation though.

Maybe because of "animate=no", tested it, yes, set "animate=yes" then we can see the healing.

Interesting is also, that (I let two minotaur fight), if Side 1 turn is active, the other minotaur isn't a stone yet, so he can be attacked. Until his turn begins.

**Comment by babaissarkar** [comment]
> For me it is working as intented. They turn to stone and heal 10 hitpoints.

Does that happen when you start the scenario with a Forgotten Minotaur already on your or somebody else's side? How did you create your Minotaurs?

**Comment by Refumee** [comment]
> > For me it is working as intented. They turn to stone and heal 10 hitpoints.
> 
> Does that happen when you start the scenario with a Forgotten Minotaur already on your or somebody else's side? How did you create your Minotaurs?

I started a local multiplayer game, with War of Legends Era.
Started with :debug and then created a forgotten minotaur.

**Comment by babaissarkar** [comment]
Tests:
1. With current turn at 1 (morning), create a For. Mino. using debug mode or `[unit]`. They can be move around my next turn, when they petrify.

**Comment by babaissarkar** [comment]
> > > For me it is working as intented. They turn to stone and heal 10 hitpoints.
> > 
> > 
> > Does that happen when you start the scenario with a Forgotten Minotaur already on your or somebody else's side? How did you create your Minotaurs?
> 
> I started a local multiplayer game, with War of Legends Era. Started with :debug and then created a forgotten minotaur.

Which version of wesnoth are you using? (I can reproduce it using exactly the same steps on 1.19.2)

**Comment by Refumee** [comment]
> > > > For me it is working as intented. They turn to stone and heal 10 hitpoints.
> > > 
> > > 
> > > Does that happen when you start the scenario with a Forgotten Minotaur already on your or somebody else's side? How did you create your Minotaurs?
> > 
> > 
> > I started a local multiplayer game, with War of Legends Era. Started with :debug and then created a forgotten minotaur.
> 
> Which version of wesnoth are you using? (I can reproduce it using exactly the same steps on 1.19.2)

Wesnoth Version 1.18.2
War of Legens Version 1.2.7.59

**Comment by babaissarkar** [comment]
Still reproducible. No idea how it's not happening in your version.

**Comment by babaissarkar** [comment]
One of the problems is that when an unit is created using [unit] the recruit event is not being called.

**Comment by Refumee** [comment]
> Still reproducible. No idea how it's not happening in your version.

In my version they can't move.
Maybe a bug from Wesnoth 1.19?
I also need to add, if I create them via debug, they aren't turned to stone. I think "unit placed" is better, than "prerecurit", that also works with the debug tool.

**Comment by babaissarkar** [comment]
`unit placed` is definitely the one to use. For some weird reason, it refuses to work for me either on 1.18 or 1.19.

**Comment by knyghtmare** [comment]
So far this I have fixed the spawning part of the event, but the event which handles existing Forgotten Minotaur units on the map is still bugged.
![image](https://github.com/user-attachments/assets/00beccac-247b-4e5e-b8a7-f0ca5dd3e542)

**Comment by Refumee** [comment]
Whats wrong with it? They are petrified and it is daytime.

**Comment by knyghtmare** [comment]
They are petrified on afternoon time. They should be petrified on morning as well, which is not happening.

**Comment by Refumee** [comment]
> They are petrified on afternoon time. They should be petrified on morning as well, which is not happening.

I see. On what version you are testing this?
It seems that it's working for me on 1.18.2.

**Comment by Refumee** [comment]
> They are petrified on afternoon time. They should be petrified on morning as well, which is not happening.

Could you send me the current code for the forgotten minotaur. It seems you are working on a different code base.
