### ISSUE TITLE
Drakes: base frame update for Smasher and Shockbringer

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#167]
- Would be super nice if they could get a slight base frame update.
- Nothing fancy, just subbing the Katana for a Warhammer.

**Comment by knyghtmare** [comment]
@babaissarkar I don't suppose you can help on this one?

**Comment by babaissarkar** [comment]
Will give it a try if I manage to get some free time from dev work.

**Comment by babaissarkar** [comment]
Issues:
Katana is held in reverse grip and has sheath. (Obviously that can't be done with a hammer)

**Comment by knyghtmare** [comment]
What I had in mind was just showing the unit having a hammer. Just updating
the Sprite is all that’s required. Maybe we can Franken some portions from
the arbiter/warden/enforcer?

**Comment by babaissarkar** [comment]
Just the base frame, and not the attack frames?

**Comment by knyghtmare** [comment]
For now, the base frame is kind of the necessary thing.
Attack frames would be a “will accept if okay and made” since art
contributions are scarce.

**Comment by babaissarkar** [comment]
![smasher_new](https://github.com/user-attachments/assets/c283bdd9-5f70-4ebe-a131-714f446d0f53)
Thoughts?
Arbitrar was a really good idea, that drake has the correct pose and is sturdy enough to hold the massive hammer!

**Comment by knyghtmare** [comment]
> ![smasher_new](https://private-user-images.githubusercontent.com/8469888/355775116-c283bdd9-5f70-4ebe-a131-714f446d0f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjYzODgsIm5iZiI6MTcyMzAyNjA4OCwicGF0aCI6Ii84NDY5ODg4LzM1NTc3NTExNi1jMjgzYmRkOS01ZjcwLTRlYmUtYTEzMS03MTRmNDQ2ZDBmNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMTAyMTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzRhM2QyNDhlODZiZWYyOGEwNzczZGM5MzU0NWU4MTY4NTI0YWMzMTIxMDIyYmQyYzViZTgzOThhMzE1NDRiYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.L1K-NeU75PLQ6V2YTl5eqArs9t3A-FFGjUAxd_KTpM0) Thoughts? Arbitrar was a really good idea, that drake has the correct pose and is sturdy enough to hold the massive hammer!

Damn, this looks super good. My one critic is that his helm is now almost like the Arbiter, so maybe some tweaks on the helm to make it more distinct to the Smasher Caste.?
or, maybe just attach the head of the current drake smasher in there?

**Comment by babaissarkar** [comment]
> I kind of realised we can even clone the arbiter/warden animation frames for the hammer slam
Yep, noticed that too.

**Comment by babaissarkar** [comment]
**Smasher:**
![smasher_new_2](https://github.com/user-attachments/assets/03244abd-2742-4a6e-9cb5-558b30c984f7)

**Shockbringer**
![shockbringer_new](https://github.com/user-attachments/assets/726cd601-60cc-4334-bb3f-7ff5c0ad2ce5)

You can probably add an lvl3 with the arbiter version (with some colors tweaked).

**Comment by knyghtmare** [comment]
> **Smasher:** ![smasher_new_2](https://private-user-images.githubusercontent.com/8469888/355781825-03244abd-2742-4a6e-9cb5-558b30c984f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjc4NDAsIm5iZiI6MTcyMzAyNzU0MCwicGF0aCI6Ii84NDY5ODg4LzM1NTc4MTgyNS0wMzI0NGFiZC0yNzQyLTRhNmUtOWNiNS01NThiMzBjOTg0ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMTA0NTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU3NzU2YzdiZDYyNjY1YWNhZDkzOGM4ZGUwNjI0MGU5MjNkYjc1MmQ0ZmE1Y2NjYWY5MmY5MjE3N2NhNWExYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LIJNpYnzudl5dy22MWizXDMxSOJTdSZjpygR7Yfp-RM)
> 
> **Shockbringer** ![shockbringer_new](https://private-user-images.githubusercontent.com/8469888/355782613-726cd601-60cc-4334-bb3f-7ff5c0ad2ce5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjc4NDAsIm5iZiI6MTcyMzAyNzU0MCwicGF0aCI6Ii84NDY5ODg4LzM1NTc4MjYxMy03MjZjZDYwMS02MGNjLTQzMzQtYmIzZi03ZmY1YzBhZDJjZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMTA0NTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDVjMWFhY2VhMjM3MTVkZjdjMTI5Y2YxY2NiNzRhMTM5N2UzZWFjMGMwOTM1MGM2NzRhZjFhMjczZWE5ZTcxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cG5DNooiMKvbWoiMHB7gkc8Z7RYqolNFYTJ-3I8-eOQ)
> 
> You can probably add an lvl3 with the arbiter version (with some colors tweaked).

The shockbringer looks like what I imagined him/her to be. The smasher's wings are currently "ribboned". Maybe we can add the existing wings of the smasher's base to this? We can then keep using his flying existing animation.
Conveniently the flying/fire animations show no weapons, so they can be kept as is. 
That just leaves the defending animation and the melee animations.

**Comment by babaissarkar** [comment]
**Smasher update:**

![smasher_new3](https://github.com/user-attachments/assets/0a7372c7-2455-4807-af41-b400637a7e8a)

**Comment by knyghtmare** [comment]
> **Smasher update:**
> 
> ![smasher_new3](https://private-user-images.githubusercontent.com/8469888/355844471-0a7372c7-2455-4807-af41-b400637a7e8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzk2NzMsIm5iZiI6MTcyMzAzOTM3MywicGF0aCI6Ii84NDY5ODg4LzM1NTg0NDQ3MS0wYTczNzJjNy0yNDU1LTQ4MDctYWY0MS1iNDAwNjM3YTdlOGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDdUMTQwMjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWJiMmEwMmFiNTk1NTM2Yjg4MjAxYjJkYWM5NzU3MzNlYmM1MDlmYzYxODc1YjVkNDAzZWFiNWEyOWU0MTlmOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kBzI_MiseuGsMFujyzDkT9FoSvU_HxmxzuwAW_KycwE)

Nice 🔥 Feel free to make a PR with the base frames any time. Animations can come later.
