### ISSUE TITLE
Retire non-functional inventory systems and adjust campaigns with WISh

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#174]
So far WISh Seems to be the best thing to use compared to the four existing things. It's best take in the sister add-on and retire the rest. I dont think anybody else uses the other 3 in WoL (I checked and WoL using authors are not even aware.)

**To remove:**
- ~Weslite inventory system~
   --> ~Broken currently. Does not have inventory storage working~
- ~SoD inventory system. Hardly works at all.~

**Not Sure:**
- ~BMR inventory system. Works, but requires huge resource pack as dependency. Kind of bugs out in some cases too. Hard-coded drops and equipment system~

**Comment by babaissarkar** [comment]
WISh is fairly stable, except for
1. The equip/unequip is unrestricted.

I'd suggest you to give WISh a test run yourself and if you think it works
better than the existing system, you can integrate it and proceed to remove
any defunct code.

(I'd like to to publish WISh as a separate addon if possible, as we
discussed earlier.)

**Comment by knyghtmare** [comment]
> (I'd like to to publish WISh as a separate addon if possible, as we
discussed earlier.)

I guess we can go with that route.

> I'd suggest you to give WISh a test run yourself and if you think it works
better than the existing system, you can integrate it and proceed to remove
any defunct code.

Yeah, I am planning too. Started the process in the SotBE rework. Need to make some basic usable pieces for the orcs.

**Comment by knyghtmare** [comment]
So, none of the existing works are affected thus, to adjust are:

- SotBE (WoL)
- Insurrection (WoL)
