### ISSUE TITLE
portrait for Sun Sorceress

### ISSUE THREAD

**Issue by sevu** [knyghtmare/War_of_Legends#2]
I looked a bit through one of you commits, and saw the new image.

mainline uses for this unit that portrait:
https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/The_Rise_Of_Wesnoth/images/portraits/dionli.png

I thought first about one of this two images::
https://github.com/wesnoth/resources/tree/master/portraits/Kitty
maybe you find use for them

Greetings

**Comment by knyghtmare** [comment]
Hi again! Sorry for being a complete slacker...but that's what university made me... :(
Anyways, I will be replacing the entire Southerners faction with the current Quenoth Elves one as initially planned so, might not be needing those milky elf portraits. Thank you for linking them though.
