### ISSUE TITLE
Art Request for Quenoth

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#200]
I got two Art Requests for Quenoth units

- [ ] Quenoth Brave (name tentative)
- [ ] Quenoth Swordsman

### Quenoth Brave
- Modify this sprite (animations optional)
![hunter](https://github.com/user-attachments/assets/54bf92cf-f09b-4470-a2fc-79966e75271d)
- Make it Quenoth style coloring (skin/hair) and armor
- remove the bolas (another unit line already has this attack)
- maybe using Quenoth Youth face (male) and hair as base?

### Quenoth Swordsman
- Modify this sprite
![warrior](https://github.com/user-attachments/assets/f8622607-863d-4e99-8e72-4cc66bd72999)
- Make it Quenoth style coloring (skin/hair) and armor
- maybe using Quenoth Youth face (male) and hair as base?

@Refumee if you would be willing to do this..?

**Comment by Refumee** [comment]
Sure, I can give it a shot.
About the brave, removing the bola and then what to do with its empty hand?
