### ISSUE TITLE
CROP_TRANSPARENT showing error in the log

### ISSUE THREAD

**Issue by rodolphecombe** [knyghtmare/War_of_Legends#207]
### Game and System Information

- **Wesnoth version: 1.18.0
- **War of Legends version: 1.2.7.66
- **OS: Windows 10

### Description of the bug

Getting hit by a unit with a daze special create the following error in the log:
"error display: unknown image function in path: CROP_TRANSPARENT"
This probably come from line 11 of theme.lua

### Steps to reproduce the behavior

1. Recruit a unit with daze (Quesnoth mystic e.g.) and attack another unit with the daze attack.
2. Check the Log

### Expected behavior

No error

**Comment by knyghtmare** [comment]
Doesn't Happen

![image](https://github.com/user-attachments/assets/634a98ea-8bbf-4bab-8c9b-7648728a60f4)

**Comment by knyghtmare** [comment]
Oh, I see
```txt
20241029 13:58:54 error config: Config contains invalid attribute name 'die sound', skipping...
20241029 14:07:06 error display: unknown image function in path: CROP_TRANSPARENT
20241029 14:10:00 error display: unknown image function in path: CROP_TRANSPARENT
```
