### ISSUE TITLE
Elemental Daemons Stats Update

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#220]
- [x] Readjust stats as they seem too OP

**Comment by knyghtmare** [comment]
Reported by @babaissarkar

**Comment by babaissarkar** [comment]
Table for L3 Daemons:
Daemons: (L3)
Air: 8x3 melee, 8x5 strong ranged, 8x4 weak ranged
Water: 18x2 melee, 14x1 SR, 8x9 WR (?)
Fire: 12x3 M, 11x4R (two attacks)
Earth: 11x3 M, 16x1R (??)

**Comment by knyghtmare** [comment]
Readjusted slightly for all elemental unit trees.
