### ISSUE TITLE
Resists defaults are source for checksum OOS

### ISSUE THREAD

**Issue by Discontinuum** [knyghtmare/War_of_Legends#42]
Related to https://github.com/wesnoth/wesnoth/issues/6650

This code
```
[units]
    #this is working as intended
    [resistance_defaults]
        id="electric"
        default="100"
        undeadfly=130
        undeadfoot=130
        undeadspirit=110
        gruefoot=110
    [/resistance_defaults]

    [resistance_defaults]
        id="energy"
        default="120"
    [/resistance_defaults]

    [resistance_defaults]
        id="arcane_focus"
        # please do not ask me why I did
        # this but this works so, yeah...
        default="( 200 - (resistance.arcane) )"
    [/resistance_defaults]
[/units]
```
causes people with WoL installed to have OOSes in games of people with no WoL installed.

In resists I see this, although this is not a WoL game

![изображение](https://user-images.githubusercontent.com/68666085/175780439-d7d1e511-f874-43a9-a0d3-c432a6c8f9d1.png)

Though it's not clear why it's not the case with other units, not undead ones (as resist defaults added to everyone)
![изображение](https://user-images.githubusercontent.com/68666085/175780532-09a9f423-8e4d-4c53-b81d-996fc5ece36e.png)

Checksum OOSes are only about undead

**Comment by knyghtmare** [comment]
[2p — Shrine of the Moon (EoM) replay 20220626-122942.gz](https://github.com/knyghtmare/War_of_Legends/files/8986070/2p.Shrine.of.the.Moon.EoM.replay.20220626-122942.gz)
[2p — Shrine of the Moon (EoM) replay 20220626-122931.gz](https://github.com/knyghtmare/War_of_Legends/files/8986071/2p.Shrine.of.the.Moon.EoM.replay.20220626-122931.gz)
Seems patched.
Maybe I patched this bug in May 2022 and didn't upload v1.2.7.15 yet...

**Comment by knyghtmare** [comment]
I uploaded v1.2.7.15 on the addons server. The resistance defaults is now moved inside `#ifdef MULTIPLAYER` so should be available only when WoL is the active era, and hopefully resolve this issue.

**Comment by knyghtmare** [comment]
> Additionally, this seems to somehow be related to the modifications included in WoL. For example, if I enable Legends Conquest, then I won't get the OOS error for that match or any future matches even if Legends Conquest is later disabled.

this just gets more messed up the further people probe into it

**Comment by knyghtmare** [comment]
v1.2.7.18 should resolve this bug since I stopped its occurrence by closing the possibilities of Legends Conquest being used outside of _World Conquest_

**Comment by knyghtmare** [comment]
Welp, that didn't work. TBH, one thing that can be done is just disabling the enemy array mod's usage with "any era" feature. A bit disappointing for players though. Would ponder on it some more.

**Comment by Discontinuum** [comment]
I have a vague feeling that you can't really succeed unless the bug in the game is fixed.

**Comment by knyghtmare** [comment]
>  the bug in the game is fixed.

So...you mean to tell me that it was an engine bug this whole time? I knew it. 3 times in a row now.

**Comment by knyghtmare** [comment]
Seems to be closed as fixed in https://github.com/wesnoth/wesnoth/commit/927660ae2c1a0417daa5c55e7ec020c8986c8d40
