### ISSUE TITLE
Aragwaithi portraits

### ISSUE THREAD

**Issue by cooljeanius** [knyghtmare/War_of_Legends#78]
I've found an artist who has been doing portrait commissions for "A New Order" for me at a reasonable rate; I'm thinking I might ask her to do some Aragwaithi portraits next. Having some guidance here would be helpful.

**Comment by knyghtmare** [comment]
The race descriptions and unit descriptions would be your goto. However, if you need an example on what they may look like: 

https://raw.githubusercontent.com/project-ethea/Invasion_from_the_Unknown/master/images/portraits/erathan.png

**Comment by cooljeanius** [comment]
Are there any specific ones you think should be prioritized?

**Comment by knyghtmare** [comment]
> Are there any specific ones you think should be prioritized?

Not really. Will there be portraits for level 1s and level 2s? Level 3s can mostly use the level 2 ones.

**Comment by cooljeanius** [comment]
Good point, I should probably just start with level 1s first, and then do higher levels later as time and money permit...

**Comment by cooljeanius** [comment]
One thing to note is that mounted units are a bit more expensive, so the Eagle Rider and Scout will probably be a little bit lower priority...

**Comment by knyghtmare** [comment]
No rush. TSoL and Cata:BoG and Cata2 are nowhere near ready for a release.

**Comment by cooljeanius** [comment]
> The race descriptions and unit descriptions would be your goto.

Speaking of which, this might be a good time to review some of the unit descriptions... for example, the description for Adepts says that they are "competent with their staves" but they don't actually have a staff attack? Their attacks are just kick and fireball...

**Comment by knyghtmare** [comment]
> Speaking of which, this might be a good time to review some of the unit descriptions... for example, the description for Adepts says that they are "competent with their staves" but they don't actually have a staff attack? Their attacks are just kick and fireball..

The person assigned to rewriting those kind of went on his usual wesbreaks so no clue when revan will return. So, if someone (preferably a writer) can get better descriptions done, I wouldn't hold them back from adding those in.

**Comment by cooljeanius** [comment]
> > Speaking of which, this might be a good time to review some of the unit descriptions... for example, the description for Adepts says that they are "competent with their staves" but they don't actually have a staff attack? Their attacks are just kick and fireball..
> 
> The person assigned to rewriting those kind of went on his usual wesbreaks so no clue when revan will return. So, if someone (preferably a writer) can get better descriptions done, I wouldn't hold them back from adding those in.

I'm working on a PR to update descriptions; I haven't filed it yet, but work is on this branch so far: https://github.com/cooljeanius/War_of_Legends/tree/egallager_description_updates

**Comment by knyghtmare** [comment]
I updated Adept and Sorceress descriptions just now lol

**Comment by knyghtmare** [comment]
also, if only text updates, make PR on master/1.16, but no wmllint and wmlindent on master since I maintain both 1.16 and 1.17 versions so one mismatch can cause conflicts

**Comment by cooljeanius** [comment]
> no wmllint and wmlindent on master since I maintain both 1.16 and 1.17 versions so one mismatch can cause conflicts

All `wmllint` did in #79 was to insert some missing newlines at some ends of files; I don't see how that can cause conflicts...

**Comment by knyghtmare** [comment]
Well, it did not..for the master branch.
Cannot really backport it since some changed files are different/absent between the 1.16 and 1.17 releases. So, can you make a new PR with the new .pot for the 1.16 branch?

**Comment by cooljeanius** [comment]
> Well, it did not..for the master branch. Cannot really backport it since some changed files are different/absent between the 1.16 and 1.17 releases. So, can you make a new PR with the new .pot for the 1.16 branch?

*just* the new `.pot`, or...?

**Comment by knyghtmare** [comment]
> just the new .pot, or...?

A fresh pot file if you wish since some strings were changed and some units were added to mainline. They are still in 1.16 of the addon. So the .pot files will be different

**Comment by cooljeanius** [comment]
> > just the new .pot, or...?
> 
> A fresh pot file if you wish since some strings were changed and some units were added to mainline. They are still in 1.16 of the addon. So the .pot files will be different

ok, see #81

**Comment by knyghtmare** [comment]
Any progress on the actual portrait?

**Comment by cooljeanius** [comment]
> Any progress on the actual portrait?

oh right it's a new month, so I ought to have money for commissioning portraits again... let me get back to that artist I've been commissioning from...

**Comment by cooljeanius** [comment]
information that would be helpful when making commission requests:
- what certain hard-to-discern features on the sprites are (like, a full list of all of their items of clothing and props)
- what sort of pose they should be in (like, which frame from which animation to base it on)
- what color to pretend the team-colored parts are

**Comment by knyghtmare** [comment]
> what certain hard-to-discern features on the sprites are (like, a full list of all of their items of clothing and props)

Nobility mage clothes. Adepts are revered in Aragwaithi society much like how mages are in Witcher society.
 
> what sort of pose they should be in (like, which frame from which animation to base it on)

No preference, maybe the base.

> what color to pretend the team-colored parts are

Green / dark green / grass green

**Comment by knyghtmare** [comment]
@cooljeanius can this be closed (since the sorceress portrait has been added) or is there any notion of another portrait?

**Comment by cooljeanius** [comment]
I intend to commission more portraits later, but it's not something I'm actively pursuing currently

**Comment by knyghtmare** [comment]
> I intend to commission more portraits later, but it's not something I'm actively pursuing currently

Okay, I will close this one so you can open another issue ticker when you decide to commission a portrait.
