### ISSUE TITLE
Latest release tagged on GitHub doesn't match latest add-on server release

### ISSUE THREAD

**Issue by cooljeanius** [knyghtmare/War_of_Legends#80]
Add-on server has 1.2.7.21, meanwhile here on GitHub there hasn't been a new tag since 1.2.2: https://github.com/knyghtmare/War_of_Legends/releases/tag/v1.2.2

**Comment by knyghtmare** [comment]
Oh, I tagged with version..but did not release as I got either too lazy or hard no promotional screenshots

Maybe next time I tag a release but you have to wait until the WoL-RPG-Pack is ready. Or any of the refining ones or the Blades of Steel part 1

**Comment by knyghtmare** [comment]
Done
