### ISSUE TITLE
[Legends Conquest] Add Deep Elves, Steelhive and Nightmares into the WC-style era

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#90]
- [x] #105
- [x] #106
- [x] #107

- [x] Add Nightmares + Steelhive Faction
- [x] Add Deep Elves + Sylvan faction
- [x] Add Undead + Nightmares

**Comment by babaissarkar** [comment]
Any commit that can be used as an example?

**Comment by knyghtmare** [comment]
> Any commit that can be used as an example?

I am handling this one. It's just the 10th and final faction so should not take me long.
