### ISSUE TITLE
[Dependency] Make Resource Addon for EoM extras

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#97]
The issue title means that there will be a dependency addon being released that will have unit files for Celestials, Therians, Warg and Elementals (I dont know how the mainline PR will go given recent comments by the monkeys)

This will allow Count Kromire and War of the Dragon to be supported by WoL (as requested)
cc @cooljeanius since he requested Count Kromire and War of the Dragon for 1.16.x and 1.18.x

**Comment by cooljeanius** [comment]
> cc @cooljeanius since he requested Count Kromire and War of the Dragon for 1.16.x

I remember asking for WotD for 1.16.x but I thought I'd directed that question to @sevu

**Comment by knyghtmare** [comment]
Anyways, I can compile the addon data from Dragon Saga as the units are present there and then package the dependency by this week. Not really complicated (for 1.16). WotD might need re-balancing as I recall it was way too much in terms of difficulty.

**Comment by knyghtmare** [comment]
No need as shown in https://forums.wesnoth.org/viewtopic.php?p=680373#p680373

Sorry, sevu. Seems someone took your porting rights.
