### ISSUE TITLE
Optimize PNG files

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/War_of_Legends#98]
Well, since https://github.com/wesnoth/wesnoth/issues/7457 is open, I cannot do anything about this for the time being:
```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```
So, these will be ignored unless the Devs fix the game client tools first.

**Comment by knyghtmare** [comment]
I will do this on MacBook...Windows effed up

**Comment by cooljeanius** [comment]
> Well, since [wesnoth/wesnoth#7457](https://github.com/wesnoth/wesnoth/issues/7457) is open

It's closed now.
